# Generated by Django 3.2.5 on 2021-08-06 02:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='role_date_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('production', models.IntegerField()),
                ('bidders', models.IntegerField()),
                ('transport', models.IntegerField()),
                ('sale', models.IntegerField()),
                ('consume', models.IntegerField()),
            ],
        ),
    ]
